In [68]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import scipy.stats as stats

In [69]:
data = pd.read_csv('data/unemployment_rate/un_r_mean_distance.csv')

In [70]:
data.head()

,state,alabama,alaska,arizona,arkansas,california,colorado,connecticut,DC,delaware,...,42,43,44,45,46,47,48,49,50,51
0,Jan,2.7,6.0,4.5,3.5,3.9,2.5,3.7,5.2,4.0,...,-0.169370,-0.287698,-0.051043,-1.234315,-1.352643,-0.997661,0.422266,1.723865,-0.051043,0.185611
1,Feb,2.7,5.8,4.5,3.5,3.9,2.5,3.8,5.1,3.9,...,-0.260915,-0.138835,-0.016756,-1.237551,-1.359630,-1.115471,0.349482,1.692356,-0.016756,0.227403
2,Mar,3.0,5.2,6.1,5.0,5.5,5.2,3.4,6.0,5.0,...,-0.850882,-0.688960,0.768333,-0.284156,-0.850882,-0.688960,0.768333,1.496980,-0.850882,-0.284156
3,Apr,13.8,13.5,13.4,10.8,16.4,12.2,8.3,11.7,14.9,...,-0.814205,0.328214,-0.168490,-0.938381,0.576566,-0.739699,0.526896,0.427555,-0.143655,-1.137062
4,May,9.6,12.7,9.0,9.6,16.4,10.2,9.6,8.8,15.9,...,-0.778152,-0.355682,0.172405,-0.989387,0.119596,-0.883770,0.726897,0.146001,-0.065234,-0.936579

In [71]:
data.set_index('state', inplace = True)

In [72]:
replacement_names = [x + '_distance' for x in data.iloc[ : , : 51].columns]

In [73]:
data.iloc[ : , 52 : ].columns = replacement_names

In [74]:
data.iloc[ : , 52 : ].columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37',
       '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
       '50', '51'],
      dtype='object')

In [75]:
for column in data.iloc[ : , 52 : ].columns:
    data.rename(columns = {column : replacement_names[int(column) - 1]}, inplace = True)

In [76]:
data

,alabama,alaska,arizona,arkansas,california,colorado,connecticut,DC,delaware,florida,...,south_dakota_distance,tennessee_distance,texas_distance,utah_distance,vermont_distance,virginia_distance,washington_distance,west_virginia_distance,wisconsin_distance,wyoming_distance
state,,,,,,,,,,,,,,,,,,,,,
Jan,2.7,6.0,4.5,3.5,3.9,2.5,3.7,5.2,4.0,2.8,...,-0.169370,-0.287698,-0.051043,-1.234315,-1.352643,-0.997661,0.422266,1.723865,-0.051043,0.185611
Feb,2.7,5.8,4.5,3.5,3.9,2.5,3.8,5.1,3.9,2.8,...,-0.260915,-0.138835,-0.016756,-1.237551,-1.359630,-1.115471,0.349482,1.692356,-0.016756,0.227403
Mar,3.0,5.2,6.1,5.0,5.5,5.2,3.4,6.0,5.0,4.4,...,-0.850882,-0.688960,0.768333,-0.284156,-0.850882,-0.688960,0.768333,1.496980,-0.850882,-0.284156
Apr,13.8,13.5,13.4,10.8,16.4,12.2,8.3,11.7,14.9,13.8,...,-0.814205,0.328214,-0.168490,-0.938381,0.576566,-0.739699,0.526896,0.427555,-0.143655,-1.137062
May,9.6,12.7,9.0,9.6,16.4,10.2,9.6,8.8,15.9,13.7,...,-0.778152,-0.355682,0.172405,-0.989387,0.119596,-0.883770,0.726897,0.146001,-0.065234,-0.936579
Jun,7.6,12.4,10.0,8.1,14.9,10.6,10.1,8.7,12.6,10.3,...,-0.860064,-0.075624,-0.467844,-1.481079,-0.108309,-0.565899,0.055116,0.218541,-0.402474,-0.729324
Jul,7.9,11.6,10.7,7.1,13.5,7.4,10.2,8.5,10.5,11.4,...,-1.010427,0.186300,-0.430196,-1.699451,-0.321402,-0.466460,0.367622,0.295093,-0.756576,-0.756576
Aug,5.6,7.4,5.9,7.4,11.2,6.7,8.1,8.6,8.9,7.3,...,-1.253373,0.347838,-0.410631,-1.548333,-1.253373,-0.705590,0.263564,0.474249,-0.621316,-0.494905
Sep,6.7,7.2,6.5,7.2,11.1,6.4,7.7,9.0,8.3,7.2,...,-1.431980,-0.337883,0.482690,-1.021694,-1.340805,-0.474645,0.482690,0.619452,-0.839344,-0.520233
Oct,5.7,5.9,7.9,6.2,9.0,6.4,6.1,8.3,5.6,6.4,...,-1.324715,0.451893,0.254492,-1.127314,-1.571466,-0.584461,-0.189660,0.007741,-0.189660,-0.436411
Nov,4.4,6.3,8.0,6.3,8.1,6.4,8.2,7.5,5.1,6.3,...,-1.475929,-0.498366,1.169242,-1.015899,-1.763448,-0.728380,-0.210847,0.134175,-0.440862,-0.555869
Dec,3.9,5.8,7.5,4.2,9.0,8.4,8.0,7.9,5.3,6.1,...,-1.701557,0.261517,0.723417,-1.355132,-1.643820,-0.604545,0.665679,0.203779,-0.258120,-0.662283

In [77]:
distance_df = data.iloc[ : , 52 : ]
distance_df

,alabama_distance,alaska_distance,arizona_distance,arkansas_distance,california_distance,colorado_distance,connecticut_distance,DC_distance,delaware_distance,florida_distance,...,south_dakota_distance,tennessee_distance,texas_distance,utah_distance,vermont_distance,virginia_distance,washington_distance,west_virginia_distance,wisconsin_distance,wyoming_distance
state,,,,,,,,,,,,,,,,,,,,,
Jan,-0.997661,2.907138,1.132229,-0.051043,0.422266,-1.234315,0.185611,1.960520,0.540593,-0.879334,...,-0.169370,-0.287698,-0.051043,-1.234315,-1.352643,-0.997661,0.422266,1.723865,-0.051043,0.185611
Feb,-0.993392,2.791072,1.204039,-0.016756,0.471562,-1.237551,0.349482,1.936515,0.471562,-0.871312,...,-0.260915,-0.138835,-0.016756,-1.237551,-1.359630,-1.115471,0.349482,1.692356,-0.016756,0.227403
Mar,-0.931842,0.849294,1.577941,0.687373,1.092176,0.849294,-0.607999,1.496980,0.687373,0.201608,...,-0.850882,-0.688960,0.768333,-0.284156,-0.850882,-0.688960,0.768333,1.496980,-0.850882,-0.284156
Apr,-0.093984,-0.168490,-0.193325,-0.839040,0.551731,-0.491347,-1.459919,-0.615523,0.179203,-0.093984,...,-0.814205,0.328214,-0.168490,-0.938381,0.576566,-0.739699,0.526896,0.427555,-0.143655,-1.137062
May,-0.725344,0.093192,-0.883770,-0.725344,1.070154,-0.566917,-0.725344,-0.936579,0.938132,0.357236,...,-0.778152,-0.355682,0.172405,-0.989387,0.119596,-0.883770,0.726897,0.146001,-0.065234,-0.936579
Jun,-0.729324,0.839556,0.055116,-0.565899,1.656681,0.251226,0.087801,-0.369789,0.904926,0.153171,...,-0.860064,-0.075624,-0.467844,-1.481079,-0.108309,-0.565899,0.055116,0.218541,-0.402474,-0.729324
Jul,-0.466460,0.875324,0.548944,-0.756576,1.564348,-0.647782,0.367622,-0.248874,0.476415,0.802795,...,-1.010427,0.186300,-0.430196,-1.699451,-0.321402,-0.466460,0.367622,0.295093,-0.756576,-0.756576
Aug,-0.916276,-0.157808,-0.789865,-0.157808,1.443403,-0.452768,0.137152,0.347838,0.474249,-0.199945,...,-1.253373,0.347838,-0.410631,-1.548333,-1.253373,-0.705590,0.263564,0.474249,-0.621316,-0.494905
Sep,-0.246708,-0.018771,-0.337883,-0.018771,1.759137,-0.383470,0.209166,0.801802,0.482690,-0.018771,...,-1.431980,-0.337883,0.482690,-1.021694,-1.340805,-0.474645,0.482690,0.619452,-0.839344,-0.520233
Oct,-0.337710,-0.239010,0.747994,-0.090959,1.290847,0.007741,-0.140309,0.945395,-0.387060,0.007741,...,-1.324715,0.451893,0.254492,-1.127314,-1.571466,-0.584461,-0.189660,0.007741,-0.189660,-0.436411
Nov,-0.958395,0.134175,1.111739,0.134175,1.169242,0.191679,1.226746,0.824220,-0.555869,0.134175,...,-1.475929,-0.498366,1.169242,-1.015899,-1.763448,-0.728380,-0.210847,0.134175,-0.440862,-0.555869
Dec,-1.181920,-0.084908,0.896629,-1.008708,1.762691,1.416266,1.185316,1.127579,-0.373595,0.088304,...,-1.701557,0.261517,0.723417,-1.355132,-1.643820,-0.604545,0.665679,0.203779,-0.258120,-0.662283

In [ ]:
#Find the states that have an unemployment rate greater than 2 SD from the mean